recordingregx/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='blog-home'), 
    path('about/', views.about, name='blog-about'), 
    

]

recordingregx/recordingregx/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.urls import include
urlpatterns = [
    path('', include('blog.urls')), # like this it will be home directory
    path('admin/', admin.site.urls),
    #path('blog/', include('blog.urls')), #has to go to this subsite
    path('register/', user_views.register, name='register'),
    path('accounts/profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html') , name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html') , name='logout'),
    path('medialibrary/', include('medialibrary.urls'))
]

recordingregx/tasks/urls.py
from django.urls import path
# from .views import TasksView
from . import views

# urlpatterns =[
#     path('', TasksView.as_view(http_method_names=['get'])),
#     path('/<int:id>/', TasksView.as_view(http_method_names=['get'])),
#     path('/store', TasksView.as_view(http_method_names=['post'])),
#     path('/update/<int:id>', TasksView.as_view(http_method_names=['put'])),
#     path('/delete/<int:id>', TasksView.as_view(http_method_names=['delete'])),
# ]

# namespace
app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='task_list'),
    path('/store', views.TaskCreateView.as_view(), name='task_create'),
    path('/update/<int:pk>', views.TaskUpdateView.as_view(), name='task_update'),
    path('/delete/<int:pk>', views.TaskDeleteView.as_view(), name='task_delete'),
]

recordingregx/tasks/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    title=models.CharField(max_length=350)
    completed=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

recordingregx/tasks/forms.py
from django import forms
from django.forms import ModelForm
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"  # include all fields in form
        # fields=('title','completed') # include particular fileds of model in form

recordingregx/tasks/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from rest_framework.decorators import api_view
from django.http import HttpResponse
from django.views import View
from django.views.decorators.csrf import csrf_exempt
import json
from .forms import TaskForm
from .models import Task
from django.views.generic import ListView, DetailView, \
    CreateView, UpdateView, DeleteView

# @csrf_exempt
# class TasksView(View):
#     def get(self, request, id=None):
#         # return HttpResponse('GET request')
#         # return render(request, "index.html") # add this line
#         form = TaskForm()
#         tasks = Task.objects.all() # add this
#         return render(request, "index.html", {"task_form": form, "tasks": tasks, "action_uri": "/tasks/store"})

    
#     def post(self, request):
#         form = TaskForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect("/tasks")
        
#         # body_unicode = request.body.decode('utf-8')
#         # body = json.loads(body_unicode)
#         # content = body['content']
#         # return HttpResponse('POST request\r\n {}'.format(body))

#     def put(self, request, id):
#         return HttpResponse('PUT request id: {}'.format(id))

#     def delete(self, request, id):
#         return HttpResponse('DELETE request')

class TaskListView(ListView):
    paginate_by = 2
    model = Task
    form = TaskForm
    context_object_name = 'tasks'
    template_name = "task_list.html"
    
    def get_context_data(self, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        context['action_uri'] = "/tasks/store"
        context['task_form'] = TaskForm()
        return context
    
    def get_paginate_by(self, queryset):
        """
        Paginate by specified value in querystring, or use default class property value.
        """
        return self.request.GET.get('paginate_by', self.paginate_by)

class TaskDetailView(DetailView):
    model = Task

class TaskCreateView(CreateView):
    model = Task
    form_class = TaskForm
    template_name = "task_form.html"
    success_url = reverse_lazy('tasks:task_list')

class TaskUpdateView(UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "task_form.html"
    success_url = reverse_lazy('tasks:task_list')

class TaskDeleteView(DeleteView):
    model = Task
    template_name = "task_confirm_delete.html"
    success_url = reverse_lazy('tasks:task_list')

recordingregx/tasks/templates/task_confirm_delete.html
<!DOCTYPE html>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ task }}"?</p>
    <input type="submit" value="Confirm" />
</form>

recordingregx/tasks/templates/task_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if object %}Edit Task {% else %} Create New Task {% endif %}</title>
</head>
<body>
<h3>{% if object %}Edit Task {% else %} Create New Task {% endif %}</h3>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" class="btn btn-success" value="Submit"></p>
    </form>
</body>
</html>

recordingregx/tasks/templates/task_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo App</title>
</head>

<body>
    <form method="post" action="{{ action_uri }}">
        {% csrf_token %}
        <!-- {{task_form}} to display all -->
        {{task_form.title}} <!-- to display particular field-->
        <button type="submit">SUBMIT</button>
    </form>
    <form action="/tasks" method="get">
        <select name="paginate_by" onchange='this.form.submit()'>
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
        </select>
    </form>
    {% for task in tasks %}
    <p>{{ forloop.counter }}. {{ task.title }} - {{ task.completed }}
        (<a href="{% url 'tasks:task_update' task.id %}">Update</a> |
        <a href="{% url 'tasks:task_delete' task.id %}">Delete</a>)
    </p>
{% endfor %}
    {% if is_paginated %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% endif %}
</body>
</html>